# Generated by Django 3.2 on 2022-03-23 22:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('current_potency', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Equipments.device')),
                ('type_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Equipments.typedevice')),
            ],
        ),
    ]
